name = "Kaleido"
uuid = "caafb194-7e8d-11e9-2724-d5981dd0806d"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Setfield = "0.3"
julia = "1.0"
